apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 3
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: supundelpagoda/react-app:1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  selector:
    app: react-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
